### ISSUE TITLE
Thanks for these fantastically researched bindep issues ❤️

### ISSUE THREAD

**Issue by Byron** [bstrie/milky#1]
It's obvious a lot of time was spent into figuring out how to minimally reproduce the issues, and even what seems to be causing them. The resulting issues are top notch and I felt a bit guilty to have not responded to them for so long which shouldn't make it seem I don't care. Quite the opposite.

That said, I noted them down in the `multidep` PR for now (#10061) to not forget and hope that once I get back into it, it will be easier to resolve those as well.

Thanks again,
Sebastian

**Comment by Byron** [comment]
Closing as this is just a fancy email.

**Comment by bstrie** [comment]
I appreciate the appreciation. :) Other than these bugs so far our experience with bindeps has been great: it's cut our clean build times in half, it's simplified our release story, it allows us to properly employ Cargo workspaces, it's improved our error messages, and it's removed a whole lot of unfortunate code that was devoted to performing terrible hacks. We want to see it mature and stabilized as soon as possible, so devoting a bit of time to making the bug reports as useful as possible is the least we can do!
